service: lost-and-found-serverless-stack

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  graphql:
    handler: src/graphql/index.handle
    events:
      - http:
          path: graphql
          method: post
          cors: true
